- hosts: opencartex
  become: yes 
  tasks: 
    - name: APT update
      apt:
        update_cache: yes

    - name: Install require packages
      apt:
        pkg:
        - apt-transport-https
        - ca-certificates
        - gnupg-agent
        - curl
        - software-properties-common
    - name: Add an Apt signing key, uses whichever key is at the URL
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Fingerprint
      shell: apt-key fingerprint 0EBFCD88

    - name: Add specified repository into sources list
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        state: present

    - name: Install require packages
      apt:
        update_cache: yes
        pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        
    - name: Test docker-ce
      shell: docker run hello-world
      register: result

    - name: Install docker-compose 
      get_url: 
        url : https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'

    - name: Copy docker-compose file
      copy: 
        src: ../../docker-compose.yml
        dest: ./ 

    - name: Test docker-compose 
      shell: docker-compose -v 
      register: result1

    # build - build image truoc khi start cac containers
    - name: Start docker-compose 
      shell: docker-compose up -d --build

    - name: Multi debug 
      debug:
        msg:
          - "Docker: {{result.stdout}}"
          - "Docker-compose: {{result1.stdout}}" 